
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDetIpP7xGwNNuOZZI_UBHKZb_ojyGTyqc',
    appId: '1:958845292344:web:752086a96dbb1466487bcd',
    messagingSenderId: '958845292344',
    projectId: 'linkair-app',
    authDomain: 'linkair-app.firebaseapp.com',
    storageBucket: 'linkair-app.firebasestorage.app',
    measurementId: 'G-LWC618Z118',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqNI6ACdNHowgnoF3hjjBXb4RpLWHMBWo',
    appId: '1:958845292344:android:3d8c68ff51b91d7e487bcd',
    messagingSenderId: '958845292344',
    projectId: 'linkair-app',
    storageBucket: 'linkair-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbWVD4CI1VlF0vIlkSIzzBLJM3te6tjw8',
    appId: '1:958845292344:ios:aa399ae00393a5ab487bcd',
    messagingSenderId: '958845292344',
    projectId: 'linkair-app',
    storageBucket: 'linkair-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbWVD4CI1VlF0vIlkSIzzBLJM3te6tjw8',
    appId: '1:958845292344:ios:aa399ae00393a5ab487bcd',
    messagingSenderId: '958845292344',
    projectId: 'linkair-app',
    storageBucket: 'linkair-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDetIpP7xGwNNuOZZI_UBHKZb_ojyGTyqc',
    appId: '1:958845292344:web:4ed165715940edce487bcd',
    messagingSenderId: '958845292344',
    projectId: 'linkair-app',
    authDomain: 'linkair-app.firebaseapp.com',
    storageBucket: 'linkair-app.firebasestorage.app',
    measurementId: 'G-VB35V1SYM6',
  );

}